spring.application.name=xpression-backend

spring.datasource.url=jdbc:h2:mem:xpressiondb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true

giphy.api.key=b3umzar3e6Sf1ziMY62NsT954VUGRsf5

jwt.secret=yourSecretKeyHereMakeItLongAndSecure123456
jwt.expiration=86400000